### PR TITLE
allow aphantasia to be pip installed

### PR DESCRIPTION
**Pull request by dribnet**
Enjoying these interesting drawing modules which are runnable from my pixray library. I've made some changes to the file locations and added a setup.py which allows aphantasia to be pip installed - which makes using the code as a library easier.

I'm posting these changes as a pull request for review, but note I haven't had much experience myself packaging python libraries and so would welcome any feedback if there are better ways to achieve this. Also haven't tested the notebooks against this change and the likely would need their imports adjusted as well. But running the notebooks in google colab could potentially be a bit easier as well as you can also use pip now from the colab to install the library.

### CODE REVIEW

**Comment by eps696** [comment]
thanks for digging into this! 
how can i test your changes before/without pushing them to the master repo? (i'm not actually experienced in git operations)

**Comment by dribnet** [comment]
Here's what I do on my local machine (from the repo directory)
```bash
git remote add pixray https://github.com/pixray/aphantasia.git   # tell git about the other repo
git fetch pixray                        # update local git knowledge with other repo - but don't change anything locally
git checkout -b pixray pixray/master    # change to a new "pixray" branch which is a copy of my code
#                                         test changes
git checkout master                     # when you are done, don't forget to go back to your own master branch
```

That's from memory - so might have flubbed one of the steps. And no foul if you don't want to re-organize your repo the same way I suggested - happy to take feedback on these changes.

**Comment by eps696** [comment]
thanks, will give it a go [just checked the changes briefly - look quite in line with my plans]

**Comment by eps696** [comment]
ok, finally checked your pr, here is few comments:
1) file locations: i'd move all importable modules (including `depth`) into subdirectory, while keeping the runnable scripts (with `main` function - `clip_fft`, `illustra`, `illustrip`) in the root dir. you may want to do it on your side at once, or i'll do it after merge.
2) googletrans: if we make it optional, we'll need to add also some check for translation argument, otherwise we'll get error. i can do that after merge.
3) i consider the version with `illustrip` equals 2.0 (there's already v.1.2b in releases). should we follow the same versioning in `setup.py`?

**Comment by eps696** [comment]
pr is merged now
with some changes [mentioned above, as of 8 dec 21], applied immediately after merge

**Pull request merged**
